# [build]
# target = [ "x86_64-unknown-linux-gnu" ] # Linux 64
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Awarnings"]


[build]
[target.x86_64-pc-windows-msvc]
# linker = "lld-link.exe"
rustflags = ["-C", "target-feature=+crt-static"] # "--cfg", "tokio_unstable" , "-Awarnings"